// Code generated by MockGen. DO NOT EDIT.
// Source: go-boilerplate-rest-api-chi/internal/author (interfaces: AuthorService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_author_service.go -package=mocks go-boilerplate-rest-api-chi/internal/author AuthorService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "go-boilerplate-rest-api-chi/internal/author/dto"
	entity "go-boilerplate-rest-api-chi/internal/entity"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthorService is a mock of AuthorService interface.
type MockAuthorService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorServiceMockRecorder
	isgomock struct{}
}

// MockAuthorServiceMockRecorder is the mock recorder for MockAuthorService.
type MockAuthorServiceMockRecorder struct {
	mock *MockAuthorService
}

// NewMockAuthorService creates a new mock instance.
func NewMockAuthorService(ctrl *gomock.Controller) *MockAuthorService {
	mock := &MockAuthorService{ctrl: ctrl}
	mock.recorder = &MockAuthorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorService) EXPECT() *MockAuthorServiceMockRecorder {
	return m.recorder
}

// CreateAuthor mocks base method.
func (m *MockAuthorService) CreateAuthor(ctx context.Context, req *dto.CreateAuthorRequest) (*entity.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthor", ctx, req)
	ret0, _ := ret[0].(*entity.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthor indicates an expected call of CreateAuthor.
func (mr *MockAuthorServiceMockRecorder) CreateAuthor(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthor", reflect.TypeOf((*MockAuthorService)(nil).CreateAuthor), ctx, req)
}

// GetAuthorByID mocks base method.
func (m *MockAuthorService) GetAuthorByID(ctx context.Context, authorID uuid.UUID) (*entity.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorByID", ctx, authorID)
	ret0, _ := ret[0].(*entity.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorByID indicates an expected call of GetAuthorByID.
func (mr *MockAuthorServiceMockRecorder) GetAuthorByID(ctx, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorByID", reflect.TypeOf((*MockAuthorService)(nil).GetAuthorByID), ctx, authorID)
}
